### ISSUE TITLE
DIAGRAMA DE CLASES

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/actividad-8-diagrama-de-clases-equipo-ggar#1]
[PRACTICA_8.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-diagrama-de-clases-equipo-ggar/files/10223605/PRACTICA_8.pdf)

**Comment by Heidi-19** [comment]
Calificación = 50%

**Comment by josealfredo79** [comment]
en los metodos no hay parametros...para realizar las operaciones, favor de corregir
![image](https://user-images.githubusercontent.com/58342642/207183912-3832028e-0afe-4332-8d59-3b39464f3111.png)

**Comment by josealfredo79** [comment]
No se han hecho las modificaciones a las sugerencias en los metodos para agregar parametros
![image](https://user-images.githubusercontent.com/58342642/207443361-a1e14d29-0862-42dd-b9d8-b74dd79fa979.png)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
